# Generated by Django 5.0.4 on 2024-04-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='forman_name',
            new_name='formal_name',
        ),
    ]
